In [1]:
import pandas as pd
import numpy as np
import glob
import pyarrow

In [2]:
print("pandas:", pd.__version__)
print("pyarrow:", pyarrow.__version__)

pandas: 2.1.4
pyarrow: 14.0.2

In [3]:
df1=pd.read_parquet('part1.parquet', engine='pyarrow')

In [4]:
df1.sample(5)

,event_id,event_name,event_timestamp,event_properties,event_receive_time,user_id,user_session_id,user_session_issued_at,user_session_count,user_properties_custom,client_platform,country_code,processing_time
2,45936e91-a76a-4e75-b2f7-d31af6241dc3,appFocus,2025-03-11 14:10:46,"[(timeStamp, 1741702246733), (onAppFocus, True)]",2025-02-11 15:10:58,92aabe08-e23e-4f74-96ff-b77b7adaadfb,0513d7cf-c5f1-4f3d-8048-5d440f32690b,2025-02-11 15:04:20,1,"[(appVersion, 0.21.19), (noAdsOwned, False), (...",Android,CA,2025-03-11 14:04:30.899
15,f2c2e817-fca4-403c-bb46-884a8bc0ddc1,transferMoney,2025-03-11 14:11:08,"[(moneyId, cash_map01), (totalMoneyInStack, 0)...",2025-02-11 15:11:18,92aabe08-e23e-4f74-96ff-b77b7adaadfb,0513d7cf-c5f1-4f3d-8048-5d440f32690b,2025-02-11 15:04:20,1,"[(adjustId, 02bfe852503880da4b13848aa21b77fa),...",Android,CA,2025-03-11 14:04:30.899
18,b6d97890-5451-4905-be9e-5e5540e661a9,appFocus,2025-03-11 14:11:47,"[(onAppFocus, False), (timeStamp, 1741702307615)]",2025-02-11 15:12:18,92aabe08-e23e-4f74-96ff-b77b7adaadfb,0513d7cf-c5f1-4f3d-8048-5d440f32690b,2025-02-11 15:04:20,1,"[(robotOwned, False), (fbInstallationId, c9ZUR...",Android,CA,2025-03-11 14:04:30.899
13,5d8bea4d-11f6-4749-b010-93c39a736170,appFocus,2025-03-11 14:10:27,"[(onAppFocus, False), (timeStamp, 1741702227710)]",2025-02-11 15:10:44,92aabe08-e23e-4f74-96ff-b77b7adaadfb,0513d7cf-c5f1-4f3d-8048-5d440f32690b,2025-02-11 15:04:20,1,"[(adjustId, 02bfe852503880da4b13848aa21b77fa),...",Android,CA,2025-03-11 14:04:30.899
0,4a2cf430-d178-45fd-8028-05ac393814a1,appBackground,2025-03-11 14:10:27,"[(timeStamp, 1741702227674), (onAppBackground,...",2025-02-11 15:10:44,92aabe08-e23e-4f74-96ff-b77b7adaadfb,0513d7cf-c5f1-4f3d-8048-5d440f32690b,2025-02-11 15:04:20,1,"[(appVersion, 0.21.19), (noAdsOwned, False), (...",Android,CA,2025-03-11 14:04:30.899

In [5]:
print(df1['event_timestamp'].min())
print(df1['event_timestamp'].max())
print(df1['processing_time'].min())
print(df1['processing_time'].max())

2025-03-11 14:10:19
2025-03-11 14:12:13
2025-03-11 14:04:30.899000
2025-03-11 14:04:30.899000

In [6]:
df2=pd.read_parquet('part2.parquet', engine='pyarrow')

In [7]:
df2.head()

,event_id,event_name,event_timestamp,event_properties,event_receive_time,user_id,user_session_id,user_session_issued_at,user_session_count,user_properties_custom,client_platform,country_code,processing_time
0,df592792-841a-4376-8a00-cca14479cd43,gameOpened,2025-03-03 08:19:20,[],2025-02-10 08:19:11,6c6028eb-04f9-421e-b957-e62729be0d6f,7fcaec19-7ccb-4e84-a368-a4f974fdf96a,2025-02-10 08:18:58,5,"[(appVersion, 0.21.13), (currentMap, 2), (noAd...",Android,SA,2025-03-11 14:06:53.773
1,3d56fe33-f02f-43d9-812e-18d9689bad12,transferMoney,2025-03-05 20:25:38,"[(moneyId, cash_map04), (totalMoneyInStack, 0)...",2025-03-05 20:25:37,590171b3-6962-4282-b175-996715e41c1a,2c1a3ff3-4c3a-4864-8a7d-3517989c8106,2025-03-05 20:23:45,156,"[(currentMap, 4), (noAdsOwned, False), (robotO...",Android,GB,2025-03-11 14:08:12.337
2,c5278e8a-bf0d-4425-b9bd-a508e68b4a14,deviceRepair,2025-03-05 20:25:39,"[(deviceRepairTimeStamp, 1741206339), (moneyIn...",2025-03-05 20:25:39,fb782ccc-1e72-49b7-8eed-847de77311cb,0c06090b-a7a3-4aed-b0e1-a53ac09f15a6,2025-03-05 20:16:07,9,"[(fbInstallationId, elzTU-8uTZCmB8thUrlEjS), (...",Android,US,2025-03-11 14:08:12.337
3,7d24539d-a7d8-408f-b2e7-c6162ac58de1,endOfDay,2025-03-05 20:25:41,"[(happyCustomer, 56), (sadCustomer, 23), (mapI...",2025-03-05 20:25:41,c104bad7-5f43-4bcf-887e-d0530963b22a,2387f936-1fe5-426a-a9d4-3303c4fae934,2025-03-05 20:00:07,2,"[(adjustId, 7d34954bf47df1228daa64d28137c61e),...",Android,FR,2025-03-11 14:08:12.337
4,3f73c490-0900-4bf2-8d31-cddbc29f4570,badCustomerResult,2025-03-05 20:25:42,"[(slapped, False)]",2025-03-05 20:25:42,9db2ae53-3cde-4139-a0c7-7478e82029b2,ebf81b0e-b582-4578-9547-78985134661a,2025-03-05 20:20:20,6,"[(adjustId, 4f38b0febabb37e016325062352a719d),...",Android,IT,2025-03-11 14:08:12.337

In [8]:
print(df2['event_timestamp'].min())
print(df2['event_timestamp'].max())
print(df2['processing_time'].min())
print(df2['processing_time'].max())

2025-03-03 08:19:20
2025-03-05 21:27:14
2025-03-11 14:06:53.773000
2025-03-11 14:08:12.337000

In [9]:
df3=pd.read_parquet('part3.parquet', engine='pyarrow')

In [10]:
df3.head()

,event_id,event_name,event_timestamp,event_properties,event_receive_time,user_id,user_session_id,user_session_issued_at,user_session_count,user_properties_custom,client_platform,country_code,processing_time
0,28a7cf05-ecec-4678-8221-3b9f138376aa,itemsGranted,2025-03-01 13:08:37,"[(item_id, zombie), (source, items_granted)]",2025-03-01 13:08:37,a8e47d1c-918c-4483-99b8-c01cf34db136,,2025-03-01 13:08:37,1,"[(noAdsOwned, False), (robotOwned, False), (fb...",Android,US,2025-03-11 14:08:12.337
1,bfe144f5-ef87-4924-a136-31b70e49bd97,interstitialLifecycle,2025-03-01 13:08:37,"[(errorInfo, no error), (id, 37de33a6651838c0)...",2025-03-01 13:08:38,43d980e6-387a-4ac5-b46b-e31ad608504d,d6d363d5-6dd0-4bdd-9cb0-9f79528d26b7,2025-03-01 13:03:12,2,"[(adjustId, 07a67216f82f008ae7627b4dedc3c870),...",IPhonePlayer,NO,2025-03-11 14:08:12.337
2,d4693af5-8c55-4e3a-896d-d3b23080dd4f,playerAbilityClaimed,2025-03-01 13:08:36,"[(playerLevel, 4), (centerLevel, 4), (mapId, m...",2025-03-01 13:08:38,453dd329-4bb5-4364-b426-c451c670c1ce,f282f537-a18d-493a-bdd8-cb4d16d4eb4e,2025-03-01 12:58:09,7,"[(adjustId, 7d8b6075e095b196fc2b4615da2f6a59),...",Android,ES,2025-03-11 14:08:12.337
3,f3d05df3-191b-4a19-b165-87994655aff3,lostCustomer,2025-03-01 13:08:40,"[(moneyId, cash_map05), (numberOfBrokenDevices...",2025-03-01 13:08:40,4493cad5-2613-458c-b947-99bf5cb0639d,53bdf05c-d778-469e-a391-94ad036d1626,2025-03-01 12:47:33,40,"[(noAdsOwned, True), (robotOwned, False), (fbI...",Android,FR,2025-03-11 14:08:12.337
4,fb175e5b-73fe-41f6-90a8-b99bd6d87094,interstitialLifecycle,2025-03-01 13:08:40,"[(id, 45f7c5074e14c2cb), (state, AdLoaded), (e...",2025-03-01 13:08:40,2f1068b8-f5d9-44d7-8d99-4148e959fe24,f9d11e71-ff30-4097-bed3-26a2a761a07f,2025-03-01 13:04:02,84,"[(adjustId, d50e1771f3b7ca737ddc93ff34561745),...",Android,US,2025-03-11 14:08:12.337

In [11]:
print(df3['event_timestamp'].min())
print(df3['event_timestamp'].max())
print(df3['processing_time'].min())
print(df3['processing_time'].max())

2025-03-01 10:19:35
2025-03-05 22:51:16
2025-03-11 14:08:12.337000
2025-03-11 14:08:12.337000

In [12]:
df4 = pd.read_parquet('part4.parquet', engine='pyarrow')

In [13]:
df4.head()

,event_id,event_name,event_timestamp,event_properties,event_receive_time,user_id,user_session_id,user_session_issued_at,user_session_count,user_properties_custom,client_platform,country_code,processing_time
0,4bd93a2e-19dd-4ffa-a0d8-b096a6347f0e,interstitialLifecycle,2025-03-02 19:23:36,"[(id, 37de33a6651838c0), (state, AdClicked), (...",2025-03-02 19:23:36,d01ef176-cac3-4d5e-99a3-959abc4dae94,ed31e82f-b418-4b04-b2b4-5e9ddb0fcdc7,2025-03-02 19:12:47,5,"[(adjustId, e22625bbecf92d026241e6faf934aa50),...",IPhonePlayer,IT,2025-03-11 14:08:12.337
1,21d47e89-a154-42c9-8b87-1ce1d7041cd9,interstitialLifecycle,2025-03-02 19:23:37,"[(id, 45f7c5074e14c2cb), (state, AdDisplayed),...",2025-03-02 19:23:37,ea74c0ad-9526-4d63-bde7-6f0e6f5c0808,fab7dcb3-9f82-4840-a598-928bbb2bd481,2025-03-02 18:14:39,2,"[(adjustId, c9706ccef5e6696ae8d26a5b9ce5eea8),...",Android,NL,2025-03-11 14:08:12.337
2,57b89080-0d18-47a8-b174-b21ff791d623,adsReturned,2025-03-02 19:23:38,"[(timeStamp, 1740943418329)]",2025-03-02 19:23:38,ea74c0ad-9526-4d63-bde7-6f0e6f5c0808,fab7dcb3-9f82-4840-a598-928bbb2bd481,2025-03-02 18:14:39,2,"[(robotOwned, False), (fbInstallationId, dOICY...",Android,NL,2025-03-11 14:08:12.337
3,6c1b8776-1f26-4ecb-88ea-5f61b1119d22,adImpression,2025-03-02 19:23:39,"[(adPlatform, Applovin), (adUnitName, 37de33a6...",2025-03-02 19:23:39,c1dbcb95-f100-4eaa-86cb-da42607871e7,3fa92680-99e3-43b0-a4ff-2c0c89c980ca,2025-03-02 19:21:32,4,"[(robotOwned, False), (fbInstallationId, czG8h...",IPhonePlayer,GB,2025-03-11 14:08:12.337
4,3929e9f9-f7df-4a3f-8c49-fe802c2479f4,lostCustomer,2025-03-02 19:23:39,"[(numberOfBrokenDevices, 9), (numberOfUnlockDe...",2025-03-02 19:23:40,d6ec90bb-b5fa-46ac-97d4-9beeed62747e,b276fb10-2019-40c8-8f1c-8c57bae8afce,2025-03-02 14:28:05,51,"[(fbInstallationId, f5LHlCxRRGaadWaWKZQynv), (...",Android,CH,2025-03-11 14:08:12.337

In [14]:
print(df4['event_timestamp'].min())
print(df4['event_timestamp'].max())
print(df4['processing_time'].min())
print(df4['processing_time'].max())

2025-03-01 14:59:46
2025-03-06 04:17:38
2025-03-11 14:08:12.337000
2025-03-11 14:08:12.337000

In [15]:
df = pd.concat([df1, df2, df3, df4])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2811413 entries, 0 to 1321598
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   event_id                object
 1   event_name              object
 2   event_timestamp         object
 3   event_properties        object
 4   event_receive_time      object
 5   user_id                 object
 6   user_session_id         object
 7   user_session_issued_at  object
 8   user_session_count      int64
 9   user_properties_custom  object
 10  client_platform         object
 11  country_code            object
 12  processing_time         datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(11)
memory usage: 300.3+ MB

In [16]:
df['event_timestamp'] = pd.to_datetime(df['event_timestamp'])
df['user_session_issued_at'] = pd.to_datetime(df['user_session_issued_at'])
df['event_receive_time'] = pd.to_datetime(df['event_receive_time'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2811413 entries, 0 to 1321598
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   event_id                object
 1   event_name              object
 2   event_timestamp         datetime64[ns]
 3   event_properties        object
 4   event_receive_time      datetime64[ns]
 5   user_id                 object
 6   user_session_id         object
 7   user_session_issued_at  datetime64[ns]
 8   user_session_count      int64
 9   user_properties_custom  object
 10  client_platform         object
 11  country_code            object
 12  processing_time         datetime64[ns]
dtypes: datetime64[ns](4), int64(1), object(8)
memory usage: 300.3+ MB

In [17]:
df_s = df.sample(50000)
df_s.head()

,event_id,event_name,event_timestamp,event_properties,event_receive_time,user_id,user_session_id,user_session_issued_at,user_session_count,user_properties_custom,client_platform,country_code,processing_time
1004404,68cc53b3-5098-4e95-846e-7592fb562e8b,adImpression,2025-03-05 17:52:52,"[(placement, ), (adFormat, INTER), (adSource, ...",2025-03-05 17:52:53,a72c660a-c5f4-41c9-98e4-8b4c9f6f1b35,167b3de6-85ad-4212-a9af-2b243147bb4e,2025-03-05 17:50:29,13,"[(fbInstallationId, e68VdjuRSVaQ5cp8BLFGvj), (...",Android,IN,2025-03-11 14:08:12.337
221155,4a08920e-8c89-468e-99d8-9f03d7626bad,adsReturned,2025-03-01 15:15:51,"[(timeStamp, 1740842151394)]",2025-03-01 15:15:51,429f462f-568e-4c69-8525-84ba7fa4093b,96a79c6c-2970-400e-97fa-faa0727f7d04,2025-03-01 08:29:29,1,"[(robotOwned, False), (fbInstallationId, c_iW7...",IPhonePlayer,IT,2025-03-11 14:08:12.337
413227,e3d743da-b1d5-457f-ae63-304ee203e0f4,currencyGranted,2025-03-04 20:00:01,"[(source, economy_granted), (currency_id, cash...",2025-03-04 20:00:01,64f02e1b-daa7-46b4-9b13-71c817063a6f,,2025-03-04 20:00:01,3,"[(noAdsOwned, False), (robotOwned, False), (fb...",Android,US,2025-03-11 14:08:12.337
967412,8d89af3c-dc2a-4547-9da3-c847cfc6f106,rvLifecycle,2025-03-05 17:12:07,"[(id, 4b8754e43e3fae1b), (state, AdReceivedRew...",2025-03-05 17:12:07,02089a2a-3c11-4072-9173-cafa03a3e548,c4430511-56ae-4c7d-8d08-b1bf0ee23a79,2025-03-05 17:02:26,72,"[(adjustId, 49557d9d04d60b70884e74d1dd19e0e7),...",Android,IN,2025-03-11 14:08:12.337
762337,8c917c45-162d-478b-9ae9-a3d6ea442115,itemsGranted,2025-03-01 18:26:06,"[(source, items_granted), (item_id, zombie)]",2025-03-01 18:26:06,527c3e4b-da37-4dc5-a07d-e3520cd214da,,2025-03-01 18:26:06,1,"[(currentMap, 1), (noAdsOwned, False), (robotO...",Android,US,2025-03-11 14:08:12.337

In [18]:
df_s['user_id'].nunique()

5398

In [19]:
df_s['event_name'].value_counts()

event_name
tokenCashout             6689
lostCustomer             4797
interstitialLifecycle    3686
rvLifecycle              3034
appBackground            2919
transferMoney            2805
appFocus                 2758
deviceBroken             2527
deviceRepair             2242
achievementUpdated       2034
badCustomerResult        1593
currencyGranted          1417
upgradeProgression       1367
adImpression             1366
badCustomerEntered       1336
deviceUpgrade            1272
adsStart                 1258
adsReturned              1257
currencySpent            1149
endOfDay                  677
unlockProgression         670
deviceUnlocked            624
endOfNight                614
offerClaim                244
buttonClick               233
boosterClaimed            189
_sessionStart             182
gameOpened                171
itemsGranted              162
skinOpened                139
playerAbilityClaimed      117
zoneUnlocked               96
achievementClaimed         88
helperUnlocked             50
skinActivated              42
gamerRoadClaimed           40
_identityCreate            37
firstOpen                  31
screenViewed               22
gameClosed                 22
hapticOnOff                14
musicOnOff                 11
soundOnOff                  8
purchaseCompleted           4
inAppPurchase               3
starterPack                 2
specialPack                 1
gem2                        1
Name: count, dtype: int64

In [20]:
print(df_s['event_timestamp'].min())
print(df_s['event_timestamp'].max())

2025-03-01 10:21:12
2025-03-06 04:16:27

In [21]:
df['event_name'].nunique()

62

In [22]:
df['event_name'].unique()

array(['appBackground', 'appFocus', 'tokenCashout', 'gameOpened',
       'firstOpen', 'transferMoney', 'unlockProgression',
       'deviceUnlocked', 'deviceRepair', 'endOfDay', 'badCustomerResult',
       'adsReturned', 'achievementUpdated', 'buttonClick', 'lostCustomer',
       'adImpression', 'badCustomerEntered', 'currencyGranted',
       'rvLifecycle', 'interstitialLifecycle', 'deviceBroken',
       'currencySpent', 'offerClaim', 'upgradeProgression', 'adsStart',
       'deviceUpgrade', 'endOfNight', 'boosterClaimed', 'gameClosed',
       'gamerRoadClaimed', 'achievementClaimed', 'zoneUnlocked',
       'itemsGranted', 'playerAbilityClaimed', 'skinOpened',
       '_sessionStart', '_identityCreate', 'musicOnOff', 'hapticOnOff',
       'soundOnOff', 'skinActivated', 'helperUnlocked',
       'purchaseCompleted', 'starterPack', 'screenViewed', 'gem2',
       'inAppPurchase', 'specialPack', 'robot', 'gamerRoadPremium',
       'noAds24HoursOffer', 'energyModifierGranted', 'gem1', 'robot3Days',
       'superStarterPack', 'gem6', 'gem4', 'standardPack', 'noAds24Hours',
       'notificationPermission', 'gem3', 'noAds'], dtype=object)

In [23]:
# raw_data
# df.to_csv("D:/game_data/user_log.csv", index=False, encoding="utf-8-sig")

In [24]:
df_s.to_csv("D:/game_data/user_sample.csv", index=False, encoding="utf-8-sig")